# Generated by Django 2.2 on 2025-09-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0076_auto_20220322_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='activity_uuid',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='adp_fossil_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='adpe',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='adpf',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ap',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ap_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='cpc_classification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='cru',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='eee',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='eet',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ep',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='epfreshwater_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='epmarine_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='epterrestrial_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='faetp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fw',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='geography',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='geography_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gwp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gwpbiogenic_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gwpfossil_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gwpluluc_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gwptotal_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='htp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='hwd',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='maetp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='mer',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='mfr',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='nhwd',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='nom15804_a2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='nrsf',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='odp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='odp_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='penre',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='penrm',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='penrt',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pere',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='perm',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pocp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pocp_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='product_uuid',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='rsf',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='rwd',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sm',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='tetp',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='wdp_a2',
            field=models.FloatField(help_text='Valor de tipo double precision.', null=True),
        ),
    ]
